"""add processed_files table

Revision ID: bc64970a04bd
Revises: be331c9f4fa7
Create Date: 2025-08-08 12:34:23.394839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc64970a04bd'
down_revision = 'be331c9f4fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_file_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('processed_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_files_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_files_uploaded_file_id'), ['uploaded_file_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processed_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_files_uploaded_file_id'))
        batch_op.drop_index(batch_op.f('ix_processed_files_customer_id'))

    op.drop_table('processed_files')
    # ### end Alembic commands ###
