"""add status to uploaded_files

Revision ID: be331c9f4fa7
Revises: 1126403ee424
Create Date: 2025-08-08 12:21:22.452473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be331c9f4fa7'
down_revision = '1126403ee424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True, default="Processing"))
        batch_op.create_index(batch_op.f('ix_uploaded_files_status'), ['status'], unique=False)

    op.execute("UPDATE uploaded_files SET status='Processing' WHERE status IS NULL")
    # ### end Alembic commands ###
    with op.batch_alter_table("uploaded_files") as batch_op:
            batch_op.alter_column(
                "status",
                existing_type=sa.String(20),
                nullable=False,
                server_default=None,
            )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
